# Generated by Django 5.0.2 on 2024-03-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_img',
            field=models.ImageField(upload_to='photos/img/%y/%m/%d'),
        ),
    ]
